#! /bin/bash

if [ $1 ]
then
    source .env
    docker build . -t vax
    docker run -ti -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION} -e VACCINE_PROVIDER=$1 -e EMAILS=${EMAILS} -e ZIPCODE=${ZIPCODE} -e VERSION=7 vax
else
    echo "Usage: ./launch [CVS|RiteAid]"
fi
